- name: Create UI project directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id | default(ansible_user) }}/annotation-ui"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user_id | default(ansible_user) }}"
    group: "{{ ansible_user_id | default(ansible_user) }}"

- name: Clone UI repository
  ansible.builtin.git:
    repo: "https://github.com/rejuve-bio/annotation-tool.git"
    dest: "/home/{{ ansible_user_id | default(ansible_user) }}/annotation-ui"
    version: writer
    force: yes

- name: Copy .env file to project directory
  ansible.builtin.copy:
    src: "templates/ui.env"
    dest: "/home/{{ ansible_user_id | default(ansible_user) }}/annotation-ui/.env"
    mode: '0644'

- name: Copy Dockerfile to project directory
  ansible.builtin.copy:
    src: "files/Dockerfile"
    dest: "/home/{{ ansible_user_id | default(ansible_user) }}/annotation-ui/Dockerfile"
    mode: '0644'

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Stop and remove existing UI container
  community.docker.docker_container:
    name: annotation-ui
    state: absent
  ignore_errors: yes

- name: Build Docker image for UI
  community.docker.docker_image:
    name: annotation-ui:latest
    build:
      path: "/home/{{ ansible_user_id | default(ansible_user) }}/annotation-ui"
    source: build
    force_source: yes
  register: build_result

- name: Display build logs
  ansible.builtin.debug:
    var: build_result.stdout_lines
  when: build_result.failed

- name: Run the UI Docker container
  community.docker.docker_container:
    name: annotation-ui
    image: annotation-ui:latest
    state: started
    restart_policy: always
    ports:
      - "3000:3000" # Maps host port 3000 to container port 3000
    env_file: "/home/{{ ansible_user_id | default(ansible_user) }}/annotation-ui/.env"
    # extra_hosts:
    #   host.docker.internal: host-gateway

- name: Verify UI is running
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 3000
    delay: 10
    timeout: 60
    state: started

- name: Display deployment information
  ansible.builtin.debug:
    msg: |
      ✅ Annotation UI successfully deployed as a Docker container!
      Application is running on http://localhost:3000

      To view live logs: docker logs -f annotation-ui
